modLoader = "javafml" #mandatory
loaderVersion = "${version_range_loader}" #mandatory
license = "MIT"
issueTrackerURL = "https://github.com/Yamahari/ILikeWood-ImmersiveEngineering-Plugin/issues" #optional

[[mods]] #mandatory
modId = "ilikewoodximmersiveengineering" #mandatory
version = "${version}" #mandatory
displayName = "I Like Wood - Immersive Engineering Plugin" #mandatory
displayURL = "https://www.curseforge.com/minecraft/mc-mods/i-like-wood-immersive-engineering-plugin" #optional
logoFile = "logo.png" #optional
credits = "Yamahari and the people of Forge" #optional
authors = "Yamahari" #optional
description = '''
Adds Immersive Engineering support for I Like Wood.
'''

[[dependencies.ilikewoodximmersiveengineering]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "${version_range_forge}" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.ilikewoodximmersiveengineering]]
modId = "minecraft"
mandatory = true
versionRange = "${version_range_mc}"
ordering = "NONE"
side = "BOTH"

[[dependencies.ilikewoodximmersiveengineering]]
modId = "ilikewood"
mandatory = true
versionRange = "${version_range_ilw}"
ordering = "NONE"
side = "BOTH"

[[dependencies.ilikewoodximmersiveengineering]]
modId = "immersiveengineering"
mandatory = true
versionRange = "${version_range_ie}"
ordering = "NONE"
side = "BOTH"