modLoader = "javafml" #mandatory
loaderVersion = "[36.1.0,)" #mandatory
license = "MIT"
issueTrackerURL = "https://github.com/Yamahari/ILikeWood-ImmersiveEngineering-Plugin/issues" #optional

[[mods]] #mandatory
modId = "ilikewoodximmersiveengineering" #mandatory
version = "1.16.5-6.3.0.0" #mandatory
displayName = "I Like Wood - Immersive Engineering Plugin" #mandatory
displayURL = "https://www.curseforge.com/minecraft/mc-mods/i-like-wood-immersive-engineering-plugin" #optional
logoFile = "logo.png" #optional
credits = "Yamahari and the people of Forge" #optional
authors = "Yamahari" #optional
description = '''
Adds Immersive Engineering support for I Like Wood.
'''

[[dependencies.ilikewoodximmersiveengineering]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[36.1.0,)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.ilikewoodximmersiveengineering]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ilikewoodximmersiveengineering]]
modId = "ilikewood"
mandatory = true
versionRange = "[1.16.5-6.3.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ilikewoodximmersiveengineering]]
modId = "immersiveengineering"
mandatory = true
versionRange = "[1.16.5-4.2.4-134,)"
ordering = "NONE"
side = "BOTH"